dist: xenial
sudo: required
language: python
python:
  - "3.7"
services:
  - docker
env:
  global:
    - PREFIX=gtcg/xenon
    - TAG=dev
  matrix:
    - PORT=10022 SCH=gridengine
    - PORT=10023 SCH=slurm
install:
  - pip install -r test-requirements.txt
  - docker pull $PREFIX-$SCH:$TAG
  - docker run -d -p $PORT:22 --name $SCH $PREFIX-$SCH:$TAG
  - sleep 10
  - docker ps -a
  - docker cp ./ $SCH:/home/xenon
  - docker exec -t $SCH chown -R xenon:xenon /home/xenon
  - docker exec -u xenon -t $SCH ./install.sh
script:
  - cd snakemake && pytest --cov=helper_functions --cov-report=xml
  - docker exec -u xenon -t $SCH ./run.sh $SCH
after_succes:
  - python-codacy-coverage -r coverage.xml
