dist: trusty
sudo: required
language: python
python:
  - "3.6"
services:
  - docker
env:
  global:
    - PREFIX=gtcg/xenon
    - TAG=dev
  matrix:
    - PORT=10022 SCH=gridengine
    - PORT=10023 SCH=slurm
install:
  - docker pull $PREFIX-$SCH:$TAG
  - docker run -d -p $PORT:22 --name $SCH $PREFIX-$SCH:$TAG
  - sleep 10
  - docker ps -a
  - docker cp ./ $SCH:/home/xenon
  - docker exec -t $SCH-$MODE chown -R xenon:xenon /home/xenon
  - docker exec -u xenon -t $SCH-$MODE ./install.sh
script:
  - docker exec -u xenon -t $SCH ./run.sh $SCH
