dist: xenial
sudo: required
language: python
python:
  - "3.7"
services:
  - docker
env:
  global:
    - PREFIX=gtcg/xenon
  matrix:
    - PORT=10022 SCH=gridengine TAG=6
    - PORT=10023 SCH=slurm TAG=17
    - PORT=10024 SCH=slurm TAG=19
install:
  - pip install -r test-requirements.txt
  - docker run -d -p $PORT:22 --name $SCH-$TAG $PREFIX-$SCH:$TAG
  - sleep 10
  - docker ps -a
  - docker cp ./ $SCH-$TAG:/home/xenon
  - docker exec -t $SCH-$TAG chown -R xenon:xenon /home/xenon
  - docker exec -u xenon -t $SCH-$TAG ./install.sh
script:
  - cd snakemake && pytest --cov=helper_functions --cov-report=xml
  - snakemake -np
  - docker exec -u xenon -t $SCH-$TAG ./run.sh $SCH
after_succes:
  - python-codacy-coverage -r coverage.xml
