---
channels:
  - conda-forge
  - bioconda
  - nlesc
dependencies:
  - snakemake=5.10.0
  - xenon-cli=3.0.4
  - jq=1.6
  - pip
  - pip:
      - git+https://github.com/yatiml/yatiml.git@e14cf8e88f9a6f79634aaaea562b47eccb1a2af4  # yatiml
